### ISSUE TITLE
Change to 4 epoch block header maturity requirement.

### ISSUE THREAD

**Issue by jordanmack** [ickb/proposal#1]
There is a change to the 4 epoch block header maturity requirement that was [mentioned](https://github.com/phroi/CKBpp/blob/master/README.md#nervosdao-gotchas). The CKB2021 hard fork, which is scheduled to occur on May 10th, will remove this requirement according to the updated [RFC](https://github.com/nervosnetwork/rfcs/pull/240).

**Comment by phroi** [comment]
Thanks for th

**Comment by phroi** [comment]
Thanks a lot @jordanmack, good to know!! I wasn't aware of the removal of 4 epoch block header maturity requirement, just removed that section!

In a broader perspective, it doesn't change much for CKB++ as the current design is still the most robust among the ones I considered!

Before publishing this proposal on talk.nervos.org, I'll take into account [Alejandro feedback on highlighting an intuitive user experience and market design](https://discord.com/channels/657799690070523914/657799690552606745/969609091448205323) and I'll go for at least another round of feedback!

Phroi

PS: reading [the document](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0036-remove-header-deps-immature-rule/0036-remove-header-deps-immature-rule.md) I was ready ready to fork and edit the RFC to improve the English wording, but [@xying21 beat me to it](https://github.com/nervosnetwork/rfcs/pull/334)! 😁
