### ISSUE TITLE
Examples of cell type

### ISSUE THREAD

**Issue by msjyryxdzzj** [ickb/proposal#12]
cell type corresponding to several types of operation can give specific examples of operation examples, as well as application scenarios.
![QQ_1725446331716](https://github.com/user-attachments/assets/e048fa29-48f9-432e-8b28-42e0f9a73ed8)
We'd like to take a closer look at the different types of transaction execution flow charts.Thx a lot！

**Comment by phroi** [comment]
Hey @msjyryxdzzj, thank you for publicly expressing your interest in iCKB by auditing the proposal and L1 scripts source code as part of the Scalebit external audit, I personally appreciate a lot!! 🙏

I would kindly request you and the full Scalebit audit team to use Github links to point out to the exact code you would like to review in each occasion (specific commit + specific lines), like the following: https://github.com/ickb/v1-core/blob/29170d139f6c320fe2588131f124f8de788dd50a/scripts/contracts/ickb_logic/src/entry.rs#L39-L69

It's really easy, try it out!! :hugs:

> We'd like to take a closer look at the different types of transaction execution flow charts.

No flow charts are available at the moment, sorry about that!

> cell type corresponding to several types of operation can give specific examples of operation examples

[For context you should be familiar with the underlying NervosDAO](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0023-dao-deposit-withdraw/0023-dao-deposit-withdraw.md). By now I'm one of the best expert on the topic, so feel free to ask if you don't understand some details!!

After that, feel free to look at the described examples and let me know how can I help you understand them better:
- [Deposit Phase 1](https://github.com/ickb/proposal?tab=readme-ov-file#deposit-phase-1)
- [Deposit Phase 2](https://github.com/ickb/proposal?tab=readme-ov-file#deposit-phase-2)
- [Withdrawal](https://github.com/ickb/proposal?tab=readme-ov-file#withdrawal)

Love & Peace, Phroi

**Comment by phroi** [comment]
@msjyryxdzzj do you have any specific question that you may want to ask regarding this issue?

**Comment by phroi** [comment]
Thank you again @msjyryxdzzj for taking your time to understand and review the iCKB proposal and Scripts 🙏
