### ISSUE TITLE
example for limit order

### ISSUE THREAD

**Issue by msjyryxdzzj** [ickb/proposal#13]
Could you elaborate on the role and purpose of the limt order and the process of executing the transaction?
![QQ_1725446627909](https://github.com/user-attachments/assets/dcee7aac-915f-4314-98c0-e026e1f08bb6)

like Validate for what？More on some design thinking related content.

**Comment by phroi** [comment]
Hey @msjyryxdzzj, thank you for publicly expressing your interest in iCKB by auditing the proposal and L1 scripts source code as part of the Scalebit external audit, I personally appreciate a lot!! 🙏

I would kindly request you and the full Scalebit audit team to use Github links to point out to the exact code you would like to review in each occasion (specific commit + specific lines), like the following: https://github.com/ickb/v1-core/blob/29170d139f6c320fe2588131f124f8de788dd50a/scripts/contracts/limit_order/src/entry.rs#L62-L81

It's really easy, try it out!! :hugs:

> Could you elaborate on the role and purpose of the limt order and the process of executing the transaction?

It's kind of already well elaborated here: [Limit Order Script](https://github.com/ickb/proposal?tab=readme-ov-file#limit-order-script)

Can you point out what exactly you would like to be elaborated more?

> like Validate for what？More on some design thinking related content.

This is the full code block:

```rust
    // Validate actions
    for [Order {
        data: in_maybe_data,
        has_master: in_has_master,
    }, Order {
        data: out_maybe_data,
        has_master: out_has_master,
    }] in metapoint_2_order.into_values()
    {
        match (in_maybe_data, in_has_master, out_maybe_data, out_has_master) {
            // Mint Order
            (None, false, Some(_), true) => (),
            // Melt Order
            (Some(_), true, None, false) => (),
            // Match Order
            (Some(i), false, Some(o), false) => validate(i, o)?,
            // Every other configuration is invalid
            _ => return Err(Error::InvalidConfiguration),
        }
    }
```

As you can see it validates the particular action involved:
- [Mint](https://github.com/ickb/proposal#mint-limit-order)
- [Match](https://github.com/ickb/proposal?tab=readme-ov-file#match-limit-order)
- [Melt](https://github.com/ickb/proposal?tab=readme-ov-file#melt-limit-order)

If the action does not have the cell configuration of one of these actions, then it's an `InvalidConfiguration`.

@msjyryxdzzj which points of this validation are not clear?

Love & Peace, Phroi

**Comment by phroi** [comment]
**Side node**: this issue is very similar to issue #11. Feel free to either continue [this conversation on that issue](https://github.com/ickb/proposal/issues/11) or make sure to [review that issue](https://github.com/ickb/proposal/issues/11) before continuing here :pray:

**Comment by phroi** [comment]
Thank you again @msjyryxdzzj for taking your time to understand and review the iCKB proposal and Scripts 🙏
