### ISSUE TITLE
Meaning of Receipt's data

### ISSUE THREAD

**Issue by msjyryxdzzj** [ickb/proposal#14]
![QQ_1725446759918](https://github.com/user-attachments/assets/4d6b73ad-7d02-4409-acaf-43a34479522d)
What is the meaning of each field in the recipt data? Can you give an example of an application scenario?

**Comment by phroi** [comment]
Hey @msjyryxdzzj, thank you for publicly expressing your interest in iCKB by auditing the proposal and L1 scripts source code as part of the Scalebit external audit, I personally appreciate a lot!! 🙏

I would kindly request you and the full Scalebit audit team to use Github links to point out exactly which part of the proposal you would like to review in each occasion (specific commit + specific headings), like the following: https://github.com/ickb/proposal/tree/e10a8e8fcacb2a7d52b04c65c4222a0f79055c1e#deposit-phase-1

It's really easy, try it out!! :hugs:

> What is the meaning of each field in the receipt data? Can you give an example of an application scenario?

[As you can see from the proposal ](https://github.com/ickb/proposal#deposit-phase-1):

>  - `union_id` all zero, it's reserved for future updates to data encoding (4 bytes)
>  - `deposit_quantity` keeps track of the quantity of deposits (4 bytes)
>  - `deposit_amount` keeps track of the single deposit unoccupied capacity (8 bytes)

I'd like to add that:

- `union_id` is the version of the receipt data and it's currently unused. I'm keeping it in the remote possibility that iCKB Scripts are deployed in an upgradable manner. At that point a future revision of the script could encode different data with a v2. For now must be equal to zero.
- `deposit_amount` keeps track of the single deposit unoccupied capacity. To understand this you must be familiar with the concepts of [cell occupied capacity](https://github.com/nervosnetwork/ckb/wiki/Occupied-Capacity) and [NervosDAO](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0023-dao-deposit-withdraw/0023-dao-deposit-withdraw.md). Deposit used in the context of iCKB is a very specific cell: a NervosDAO deposit with iCKB Script as lock. This cell has a capacity, an occupied capacity and an unoccupied capacity (= capacity - occupied capacity).
- `deposit_quantity` keeps track of the quantity of deposits. A tx may have many iCKB deposits in output with a specific `deposit_amount`. This counter keep track of how many deposits with `deposit_amount` of unoccupied capacity this specific receipt is tracking. Keep in mind that multiple receipts for a specific `deposit_amount` may exists in output, each one keep track of a particular subset of deposits.

@msjyryxdzzj all this said, what should I explain more?

Love & Peace, Phroi

**Comment by phroi** [comment]
**Side Note**: I improved the proposal with the information detailed before. Additionally I removed the unused field `union_id` as [indeed was unused with a non-upgradable deployment](https://github.com/ickb/proposal/commit/2c1542ddbd485f97f2ecb7bfdc8858d8c78b4de3).

Both these changes should make it easier for you to understand Receipt Data :hugs:

**Comment by phroi** [comment]
Thank you again @msjyryxdzzj for taking your time to understand and review the iCKB proposal and Scripts 🙏
