### ISSUE TITLE
Deposited vs Receipted Comparison in `check_output`

### ISSUE THREAD

**Issue by jlguochn** [ickb/proposal#16]
Hi there,
I was reviewing the check_output function and noticed that it compares deposited and receipted as follows:
https://github.com/ickb/v1-core/blob/92be3c3ea31226dece0f7235b12cf5b96766a8a3/scripts/contracts/ickb_logic/src/entry.rs#L132-L137

From what I understand:
deposited is incremented by 1 each time a deposit occurs, which seems to track the number of deposit cells
https://github.com/ickb/v1-core/blob/92be3c3ea31226dece0f7235b12cf5b96766a8a3/scripts/contracts/ickb_logic/src/entry.rs#L109

receipted is incremented by u128::from(deposit_quantity), which appears to track the total deposit quantity.
https://github.com/ickb/v1-core/blob/master/scripts/contracts/ickb_logic/src/entry.rs#L119

Given that deposited counts the occurrences while receipted tracks the total quantity, it seems these two values represent different concepts, I was wondering if this comparison might lead to an unexpected mismatch error?

**Comment by phroi** [comment]
Hey @jlguochn, thank you for publicly expressing your interest in iCKB by auditing the proposal and L1 scripts source code as part of the Scalebit external audit, I personally appreciate a lot!! 🙏

In particular I really appreciate this question (that was never asked before) and the use of links (if you want, feel free also to include the relevant code as code blocks).

> Given that deposited counts the occurrences while receipted tracks the total quantity, it seems these two values represent different concepts, I was wondering if this comparison might lead to an unexpected mismatch error?

So we agree that the check is already sensitive, but maybe too sensitive, right?

[If you look at the proposal](https://github.com/ickb/proposal/tree/1f1405e5a0d10d046703f5186058f8c8063f990d?tab=readme-ov-file#deposit-phase-1):
> A single receipt tracks a group of deposits with same unoccupied capacity in the current tx output. Multiple receipts for a specific unoccupied capacity may be created where each one keep track of a different group of deposits. [...] A tx may create many deposits with the same unoccupied capacity. This counter [`deposit_quantity`] keeps track of how many deposits with the same unoccupied capacity are being tracking in the current tx by this specific receipt.

The starting point is that in a single tx many receipts may be created and many more deposits may be created.

Let's make an example, let's assume the following iCKB deposits are created in the current tx:

1. 100082 CKB, so 100000 CKB of unoccupied capacity (100082 CKB - 82 CKB).
2. 100083 CKB, so 100001 CKB of unoccupied capacity.
3. 100084 CKB, so 100002 CKB of unoccupied capacity.
4. 100082 CKB, so 100000 CKB of unoccupied capacity.
5. 100084 CKB, so 100002 CKB of unoccupied capacity.
6. 100083 CKB, so 100001 CKB of unoccupied capacity.
7. 100082 CKB, so 100000 CKB of unoccupied capacity.
8. 100082 CKB, so 100000 CKB of unoccupied capacity.

They could be tracked by the following receipts:

1. `deposit_amount` (DA) : 100000, `deposit_quantity` (DQ) : 4.
2. DA : 100001, DQ : 2.
3. DA : 100002, DQ : 2.

But also a valid receipt configuration could be the following:

1. DA : 100002, DQ : 2.
2. DA : 100000, DQ : 1.
3. DA : 100001, DQ : 2.
4. DA : 100000, DQ : 2.
5. DA : 100000, DQ : 1.

What matters is that that the receipt accounting for each deposit size checks out.

@jlguochn does it make more sense now?

**Comment by jlguochn** [comment]
@phroi  OK, I see. Thank you so much for your detailed explanation and the examples.

**Comment by phroi** [comment]
No worries, my pleasure!!

@jlguochn do you have any more doubts on this? If so, feel free to ask more questions, otherwise feel free to close the issue 🤗

**Comment by jlguochn** [comment]
Thanks!  I'll close the issue now.

**Comment by phroi** [comment]
Thank you again @jlguochn for taking your time to understand and review the iCKB proposal and Scripts 🙏
