### ISSUE TITLE
Description of iCKB rule

### ISSUE THREAD

**Issue by XuJiandong** [ickb/proposal#4]
> The total iCKB value of input tokens and input receipts must be bigger or equal to the total iCKB value of output tokens.

According to the code, it should be "equal" only:
https://github.com/ickb/v1-core/blob/1647af2aadcc5b57bc876fe64c5929dbedf67ea1/scripts/contracts/ickb_logic/src/entry.rs#L32

**Comment by phroi** [comment]
Good catch, I recently updated the iCKB script code to prevent a failure mode that was happening on Testnet: https://github.com/ckb-js/lumos/issues/735

I forgot to update the proposal, thank you!! :pray:
