### ISSUE TITLE
More rules on deposit_quantity and deposit_amount

### ISSUE THREAD

**Issue by XuJiandong** [ickb/proposal#5]
As in "Example of deposit phase 1:",`deposit_quantity * deposit_amount` should be equal to some value from deposit cell.

**Comment by phroi** [comment]
I'm sorry, I don't understand what's this issue is about. Can you explain a bit more? For starters, is this an issue with the proposal or with the script implementation?

**Comment by phroi** [comment]
> `deposit_quantity * deposit_amount`should be equal to some value from deposit cell

Strictly speaking, `deposit_quantity * deposit_amount` is nothing to iCKB in deposit phase one. Sure, it could be the total amount deposited (assuming that as usual only deposits of a single size are used), but iCKB does not use this amount, not in the proposal, not in the iCKB script itself.

On the other side, in [deposit phase 2](https://github.com/ickb/proposal#deposit-phase-2) the receipt value is calculated with `receipt_iCKB_value(deposit_quantity, deposit_amount, AR_m)` as documented.

Closing the issue for now, feel free to reopen it :hugs:
